---
language: php

addons:
  apt:
    packages:
    # - apache2-utils # htdigest
    - cadaver

cache:
  directories:
  - $HOME/.composer/cache/files

php:
- nightly
- 7.3
# - 7.2
- 7.0
- 5.5

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly


before_install:
- go get -u github.com/jingweno/ccat
# - pip install --user pygments
- pip install --user pexpect
- wget https://github.com/travis-util/https-security-checker/archive/master.zip --output-document=- | jar xvf /dev/stdin
- . https-security-checker-master/init-source.bash
# Disabling Xdebug - Debugger and Profiler Tool for PHP
- |
  php -r "print_r(get_loaded_extensions(TRUE));"
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    install --directory ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    php -r "print_r(get_loaded_extensions(TRUE));"
  fi


install:
- mkdir data
- mkdir public
- chmod a+rwx data public
- composer init --stability=alpha
- composer require sabre/dav


before_script:
- curl_security_check composer.lock
#^ This checks that the application doesn't use dependencies with known security vulnerabilities


script:
- php -S localhost:8000 server.php > /dev/null &
- sleep 1 # or better check socket with ncat.
- curl --digest --user user:user http://localhost:8000 | w3m -dump -T text/html # w3m can also list links
- python cadaver-pexpect.py


after_script:
- ls --almost-all --color
- ls --almost-all --color data
- ls --almost-all --color public


- composer show --latest
- $GOPATH/bin/ccat composer.json
- man htdigest
